# Generated by Django 4.2.5 on 2023-10-13 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myBlogs', '0005_alter_post_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='images',
        ),
    ]
