# Generated by Django 4.2.5 on 2023-10-13 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myBlogs', '0006_remove_post_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='images',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images/'),
        ),
    ]
