# Generated by Django 4.2.5 on 2023-10-14 11:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myBlogs', '0014_alter_post_author_alter_post_liker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='liker',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_liker', to=settings.AUTH_USER_MODEL),
        ),
    ]
