# Generated by Django 4.2.6 on 2023-10-25 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_social', '0002_like_group_friendship_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='group_picture',
            field=models.ImageField(blank=True, upload_to='profile_pics/'),
        ),
    ]
