# Generated by Django 4.2.6 on 2023-10-25 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_social', '0003_group_group_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='lives',
            field=models.TextField(default='SOME STRING', max_length=255),
        ),
        migrations.AddField(
            model_name='customuser',
            name='name',
            field=models.TextField(default='SOME STRING', max_length=255),
        ),
    ]
