# Generated by Django 4.2.5 on 2023-10-25 05:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_social', '0004_customuser_lives_customuser_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='lives',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='name',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='website',
            field=models.TextField(default='https://khiem2911.pythonanywhere.com/', max_length=255),
        ),
        migrations.AlterField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='groups_joined', to=settings.AUTH_USER_MODEL),
        ),
    ]
