# Generated by Django 4.2.5 on 2023-10-25 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_social', '0005_alter_customuser_lives_alter_customuser_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='group_picture',
            field=models.ImageField(blank=True, upload_to='group_pics/'),
        ),
    ]
