# Generated by Django 4.2.5 on 2023-10-25 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_social', '0008_replycomment_commentgroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentgroup',
            name='author',
        ),
        migrations.RemoveField(
            model_name='commentgroup',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='commentgroup',
            name='post',
        ),
        migrations.AddField(
            model_name='commentgroup',
            name='comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_social.comment'),
        ),
        migrations.AddField(
            model_name='commentgroup',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_social.group'),
        ),
    ]
