# Generated by Django 4.2.5 on 2023-10-25 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_social', '0011_commentgroup_post_grouppost_comments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouppost',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='comments', to='app_social.comment'),
        ),
    ]
