# Generated by Django 4.2.5 on 2023-10-25 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_social', '0012_alter_grouppost_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grouppost',
            name='comments',
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='app_social.grouppost'),
        ),
        migrations.DeleteModel(
            name='CommentGroup',
        ),
    ]
