# Generated by Django 4.2.5 on 2023-10-31 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_social', '0021_follow'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together=set(),
        ),
    ]
