# Generated by Django 4.2.7 on 2023-11-06 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_social', '0026_replycommentpost_commentpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replycommentpost',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repliesPost', to='app_social.commentpost'),
        ),
    ]
