# Generated by Django 4.2.7 on 2023-11-10 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_social', '0027_alter_replycommentpost_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendship',
            name='blocked',
            field=models.BooleanField(default=False),
        ),
    ]
