# Generated by Django 4.2.5 on 2023-11-11 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_social', '0028_friendship_blocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='imgcover',
            field=models.ImageField(blank=True, null=True, upload_to='imgcover/'),
        ),
    ]
