# Generated by Django 4.2.7 on 2023-11-13 02:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_social', '0031_remove_post_liked_remove_post_likes_grouppost_liked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='liked',
            field=models.TextField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='grouppost',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_Groupposts', to=settings.AUTH_USER_MODEL),
        ),
    ]
