# Generated by Django 4.2.5 on 2023-11-15 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_social', '0032_post_liked_post_likes_alter_grouppost_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouppost',
            name='images',
            field=models.ManyToManyField(blank=True, to='app_social.image'),
        ),
        migrations.AddField(
            model_name='grouppost',
            name='video',
            field=models.ManyToManyField(blank=True, to='app_social.video'),
        ),
    ]
