# Generated by Django 4.2.5 on 2023-11-22 02:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_social', '0036_fanpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post_Fanpage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('liked', models.TextField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('images', models.ManyToManyField(blank=True, to='app_social.image')),
                ('likes', models.ManyToManyField(blank=True, related_name='liked_posts_fanpage', to=settings.AUTH_USER_MODEL)),
                ('video', models.ManyToManyField(blank=True, to='app_social.video')),
            ],
        ),
    ]
