# Generated by Django 4.2.5 on 2023-11-22 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_social', '0038_post_fanpage_fanpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post_fanpage',
            name='author',
        ),
    ]
