# Generated by Django 4.2.5 on 2023-11-22 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_social', '0039_remove_post_fanpage_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagePostFanpage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images_post_fanpage/')),
            ],
        ),
        migrations.CreateModel(
            name='VideoPostFanpage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(blank=True, null=True, upload_to='videos_post_fanpage/')),
            ],
        ),
        migrations.AlterField(
            model_name='post_fanpage',
            name='images',
            field=models.ManyToManyField(blank=True, to='app_social.imagepostfanpage'),
        ),
        migrations.AlterField(
            model_name='post_fanpage',
            name='video',
            field=models.ManyToManyField(blank=True, to='app_social.videopostfanpage'),
        ),
    ]
