# Generated by Django 4.2.7 on 2023-11-24 00:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_social', '0040_imagepostfanpage_videopostfanpage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fanpage',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='fanpage_joined', to=settings.AUTH_USER_MODEL),
        ),
    ]
