# Generated by Django 4.2.7 on 2023-11-24 03:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_social', '0042_group_imgcover'),
    ]

    operations = [
        migrations.AddField(
            model_name='fanpage',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_fanpage', to=settings.AUTH_USER_MODEL),
        ),
    ]
