# Generated by Django 4.2.7 on 2023-11-27 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_social', '0045_message_room'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
        migrations.AddField(
            model_name='post',
            name='view_post',
            field=models.CharField(choices=[('public', 'Public'), ('friends', 'Friends'), ('onlyme', 'Only me')], default='public', max_length=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.TextField(max_length=255),
        ),
    ]
