# Generated by Django 4.2.5 on 2023-11-29 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_social', '0046_delete_message_delete_room_post_view_post_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='group_picture',
            field=models.ImageField(blank=True, default='/group_pics/logo2.png', upload_to='group_pics/'),
        ),
    ]
